#!/usr/bin/env node
// Validate the shape of a produced G-code file. Catches regressions where
// orc_slice returns 0 but produces malformed or truncated output.
//
// Checks:
//   1. file size within an expected band
//   2. starts with the preFlight header
//   3. contains layer-change markers + extrusion moves
//   4. ends with the filament-stats footer (the marker we know preflight
//      writes via `; estimated printing time` near EOF)
//
// Each check prints `PASS check_name` or `FAIL check_name <detail>`.
// Exits 0 if all checks pass, 1 if any fail.

const fs = require('fs');

const inPath = process.argv[2] || '/tmp/preflight-wasm-test.gcode';
if (!fs.existsSync(inPath)) {
  console.error(`FAIL: file not found ${inPath}`);
  process.exit(1);
}

const gcode = fs.readFileSync(inPath, 'utf8');
let failures = 0;

function check(name, ok, detail = '') {
  if (ok) {
    console.log(`PASS ${name}`);
  } else {
    console.log(`FAIL ${name} ${detail}`);
    failures++;
  }
}

// 1. Size band. Reference baseline for cylinder.stl + default config is
// 1.33 MB. Allow 800 KB – 3 MB to absorb upstream tweaks without
// triggering false positives.
const sizeKB = gcode.length / 1024;
check('size_range',
  sizeKB >= 800 && sizeKB <= 3000,
  `got ${sizeKB.toFixed(1)} KB (expected 800–3000)`);

// 2. Header. preFlight stamps a `; generated by preFlight` line as the
// very first line.
check('header_present',
  /^; generated by preFlight/.test(gcode),
  `first line was: ${gcode.split('\n', 1)[0]}`);

// 3. Layer-change markers. preFlight emits `;LAYER_CHANGE:N` per layer;
// cylinder.stl @ 0.2 mm layer height is ~100 layers.
const layerChanges = (gcode.match(/^;LAYER_CHANGE:/gm) || []).length;
check('layer_changes',
  layerChanges >= 50 && layerChanges <= 500,
  `got ${layerChanges} (expected 50–500)`);

// 4. Extrusion moves — G1 X… Y… E… moves are the bulk of any real slice.
const g1Extrusions = (gcode.match(/^G1 .*E[\d.\-]+/gm) || []).length;
check('extrusion_moves',
  g1Extrusions >= 1000,
  `got ${g1Extrusions} (expected ≥ 1000)`);

// 5. Filament stats footer.
check('stats_footer',
  /; estimated printing time/i.test(gcode),
  'missing "; estimated printing time" line near EOF');

// 6. No null bytes / binary junk (the bridge returns a std::string, but
// if anything truncates or mishandles it we'd see NUL or unrepresentable
// data).
const nulCount = (gcode.match(/\0/g) || []).length;
check('no_null_bytes',
  nulCount === 0,
  `found ${nulCount} NUL bytes`);

console.log(`---`);
console.log(failures === 0 ? 'PASS overall' : `FAIL overall (${failures} check(s) failed)`);
process.exit(failures === 0 ? 0 : 1);
