#!/usr/bin/env bash
# Build the preFlight WebAssembly engine (Cubby Slicer engine ABI).
#
#   BUILD_VARIANT=release|debug  (default release)  -> build-release/ or build-debug/
#   NPROC=3                      parallel compile jobs (each emcc job ~0.5-1.5 GB)
#   PREFLIGHT_SRC=../preflight   preFlight checkout at tag v1.3.0
#   WASM_DEPS=../wasm-deps       shared toolchain + dependency prefix
#   --clean                      wipe the build dir first
#
# Output: build-<variant>/{slicer.mjs,slicer.wasm,schema.json,version.json}
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PREFLIGHT_SRC="${PREFLIGHT_SRC:-$ROOT/../preflight}"
# Toolchain: a shared ../wasm-deps checkout when present, else ./toolchain (see toolchain/README.md).
if [[ -z "${WASM_DEPS:-}" ]]; then
    if [[ -f "$ROOT/../wasm-deps/env.sh" ]]; then WASM_DEPS="$ROOT/../wasm-deps"; else WASM_DEPS="$ROOT/toolchain"; fi
fi
PATCH_FILE="$ROOT/patches/preflight-wasm.patch"
PREFLIGHT_TAG="v1.3.0"
VARIANT="${BUILD_VARIANT:-release}"
JOBS="${NPROC:-3}"
BUILD_DIR="$ROOT/build-$VARIANT"

CLEAN=0
for arg in "$@"; do
    case "$arg" in
        --clean|-clean) CLEAN=1 ;;
        *) echo "unknown argument: $arg" >&2; exit 2 ;;
    esac
done
case "$VARIANT" in release|debug) ;; *) echo "BUILD_VARIANT must be release or debug" >&2; exit 2 ;; esac

# shellcheck disable=SC1091
source "$WASM_DEPS/env.sh"
command -v emcc >/dev/null || { echo "emcc not found after sourcing $WASM_DEPS/env.sh" >&2; exit 1; }
for f in libboost_log.a libqhullstatic_r.a libexpat.a libheatshrink_dynalloc.a libnlopt.a; do
    [[ -f "$WASM_DEPS_PREFIX/lib/$f" ]] || { echo "missing $WASM_DEPS_PREFIX/lib/$f - run: bash $WASM_DEPS/build-deps.sh (boost, preflight-extras, nlopt, ...)" >&2; exit 1; }
done

# --- preFlight checkout + patch (idempotent) ---------------------------------
if [[ ! -d "$PREFLIGHT_SRC/.git" ]]; then
    echo "cloning preFlight $PREFLIGHT_TAG into $PREFLIGHT_SRC"
    git clone --depth 1 --branch "$PREFLIGHT_TAG" https://github.com/oozebot/preFlight.git "$PREFLIGHT_SRC"
fi
head_tag="$(git -C "$PREFLIGHT_SRC" describe --tags --exact-match 2>/dev/null || true)"
if [[ "$head_tag" != "$PREFLIGHT_TAG" ]]; then
    echo "WARN: $PREFLIGHT_SRC is at '${head_tag:-$(git -C "$PREFLIGHT_SRC" rev-parse --short HEAD)}', expected $PREFLIGHT_TAG" >&2
fi
if git -C "$PREFLIGHT_SRC" apply --reverse --check "$PATCH_FILE" >/dev/null 2>&1; then
    echo "patch: already applied"
elif git -C "$PREFLIGHT_SRC" apply --check "$PATCH_FILE" >/dev/null 2>&1; then
    git -C "$PREFLIGHT_SRC" apply "$PATCH_FILE"
    echo "patch: applied"
else
    echo "ERROR: patches/preflight-wasm.patch neither applies nor is already applied to $PREFLIGHT_SRC." >&2
    echo "       Reset the checkout (git checkout -- . && git clean -fd && git checkout $PREFLIGHT_TAG) and retry." >&2
    exit 1
fi

# --- configure + build ---------------------------------------------------------
[[ $CLEAN -eq 1 ]] && rm -rf "$BUILD_DIR"
LAUNCHER=()
if command -v ccache >/dev/null; then
    LAUNCHER=(-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache)
fi
if [[ ! -f "$BUILD_DIR/build.ninja" ]]; then
    emcmake cmake -S "$ROOT/wasm" -B "$BUILD_DIR" -G Ninja \
        -DBUILD_VARIANT="$VARIANT" -DPREFLIGHT_SRC="$PREFLIGHT_SRC" \
        -DWASM_DEPS_PREFIX="$WASM_DEPS_PREFIX" -DWASM_BRIDGE_DIR="$ROOT/bridge/common" \
        "${LAUNCHER[@]}"
fi
cmake --build "$BUILD_DIR" --target slicer -j"$JOBS"

for f in slicer.mjs slicer.wasm; do
    [[ -f "$BUILD_DIR/$f" ]] || { echo "ERROR: build did not produce $f" >&2; exit 1; }
done

# --- schema.json + version.json (generated by the module itself) --------------
node "$ROOT/scripts/gen-schema.mjs" "$BUILD_DIR"

ls -l "$BUILD_DIR"/slicer.mjs "$BUILD_DIR"/slicer.wasm "$BUILD_DIR"/schema.json "$BUILD_DIR"/version.json
echo "OK: $VARIANT build in $BUILD_DIR"
